joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min: 0.2
      linear_forward_max: 0.7
      linear_backwars_min: 0.2
      linear_backwars_max: 0.7
      angular_min: 0.7
      angular_max: 5.0
      steps: 3